version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: orca_postgis
    environment:
      POSTGRES_USER: orca_user
      POSTGRES_PASSWORD: orca_password
      POSTGRES_DB: orca_marine
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis_data:
